[base]
video_input = "example.mp4"
nb_persons_to_detect = "all"
person_ordering_method = "on_click"
first_person_height = 1.65
visible_side = ["auto", "front", "none"]
time_range = []
video_dir = ""
webcam_id = 0
input_size = [1280, 720]
show_realtime_results = true
save_vid = true
save_img = true
save_pose = true
calculate_angles = true
save_angles = true
result_dir = "results"

[pose]
slowmo_factor = 1.0
pose_model = "body_with_feet"
mode = "balanced"
det_frequency = 4
device = "auto"
backend = "auto"
tracking_mode = "sports2d"
predict_displacement = false
match_by = "keypoints"
max_distance = 250
min_iou = 0.2
max_unseen_time = 1.0
keypoint_likelihood_threshold = 0.3
average_likelihood_threshold = 0.5
keypoint_number_threshold = 0.3

[px_to_meters_conversion]
to_meters = true
make_c3d = true
save_calib = true
perspective_value = 10.0
perspective_unit = "distance_m"
floor_angle = "auto"
xy_origin = ["auto"]
distortions = [0.0, 0.0, 0.0, 0.0, 0.0]
calib_file = ""

[angles]
display_angle_values_on = ["body", "list"]
fontSize = 0.3
joint_angles = ["Right ankle", "Left ankle", "Right knee", "Left knee"]
segment_angles = ["Right shank", "Left shank", "Right thigh", "Left thigh", "Pelvis", "Trunk"]
correct_segment_angles_with_floor_angle = true

[post-processing]
interpolate = true
interp_gap_smaller_than = 100
fill_large_gaps_with = "last_value"
sections_to_keep = "all"
min_chunk_size = 10
reject_outliers = true
filter = true
show_graphs = true
save_graphs = true
filter_type = "butterworth"

[post-processing.butterworth]
cut_off_frequency = 6.0
order = 4

[kinematics]
do_augmentation = false
do_ik = false
filter_ik = false
ik_filter_type = "acc_minimizing"
feet_on_floor = false
use_simple_model = false
participant_mass = [55.0]
parallel_workers_kinematics = "auto"
right_left_symmetry = true
default_height = 1.7
large_hip_knee_angles = 135.0
trimmed_extrema_percent = 50
remove_individual_scaling_setup = true
remove_individual_ik_setup = true
osim_setup_path = "../OpenSim_setup"

[logging]
use_custom_logging = false
